# Generated by Django 2.2.24 on 2021-07-29 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SS_ABS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePatternItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.CreateModel(
            name='DisjunctKnowledgePatternItem',
            fields=[
                ('knowledgepatternitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SS_ABS_app.KnowledgePatternItem')),
            ],
            bases=('SS_ABS_app.knowledgepatternitem',),
        ),
        migrations.CreateModel(
            name='QuantKnowledgePatternItem',
            fields=[
                ('knowledgepatternitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SS_ABS_app.KnowledgePatternItem')),
            ],
            bases=('SS_ABS_app.knowledgepatternitem',),
        ),
    ]
